// Content layer.
//
// Sources (all JSON, all in /content, all edited in GitHub):
//   archive/      every TAM night on Eventbrite, the performers billed, series
//                 and venues — generated by scripts/import_eventbrite.py
//   legacy/       every page of the old www.tam.tv — scripts/import_oldsite.py
//   videos.json   TAM TV's YouTube films
//   artists.json  editorial overrides for artists (bio, links, legend)
//   events.json   hand-made events that aren't on Eventbrite
//   stories.json, listen.json, site.json, chorus.json
//
// Everything is indexed once at startup; pages only filter by "now".

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const here = path.dirname(fileURLToPath(import.meta.url));
export const CONTENT_DIR = process.env.CONTENT_DIR || path.join(here, '..', '..', 'content');

const read = (name) => JSON.parse(readFileSync(path.join(CONTENT_DIR, `${name}.json`), 'utf8'));

export const GENRE_NAMES = {
  blues: 'Blues', jazz: 'Jazz', soul: 'Soul & R&B', funk: 'Funk', rock: 'Rock & Indie', folk: 'Folk & Americana',
  latin: 'Latin', reggae: 'Reggae & Ska', electronic: 'Electronic', pop: 'Pop', comedy: 'Comedy', karaoke: 'Karaoke', 'open-mic': 'Open Mic & Jams',
};

// "2023-05-18" + "19:00" -> "2023-05-18T19:00:00+01:00" (London time).
export function londonISO(date, time = '00:00') {
  const guess = new Date(`${date}T${time}:00Z`);
  const tz = new Intl.DateTimeFormat('en-GB', { timeZone: 'Europe/London', timeZoneName: 'shortOffset' })
    .formatToParts(guess).find((p) => p.type === 'timeZoneName')?.value || 'GMT';
  const m = /GMT([+-]\d+)?/.exec(tz);
  const hours = m?.[1] ? Number(m[1]) : 0;
  const off = `${hours < 0 ? '-' : '+'}${String(Math.abs(hours)).padStart(2, '0')}:00`;
  return `${date}T${time}:00${off}`;
}

export function loadContent() {
  const site = read('site');
  if (process.env.SITE_URL) site.url = process.env.SITE_URL.replace(/\/$/, '');

  const venues = read('archive/venues');
  const series = read('archive/series');
  const legacy = read('legacy/pages');
  const legacyBy = Object.fromEntries(legacy.map((p) => [p.path, p]));
  const overrides = Object.fromEntries(read('artists').map((a) => [a.slug, a]));

  const events = [...read('archive/events'), ...read('events')]
    .map((e) => ({ ...e, start: e.start || londonISO(e.date, e.time || '19:00') }))
    .sort((a, b) => a.start.localeCompare(b.start));

  const artists = read('archive/performers').map((p) => {
    const o = overrides[p.slug] || {};
    const page = legacyBy[`/artists/${p.slug}`];
    return {
      ...p,
      ...o,
      legend: Boolean(o.legend ?? p.legend),
      // Bio: an editorial override wins; otherwise the old tam.tv page's text.
      bio: o.bio || (page ? page.blocks.filter((b) => b.type === 'p').map((b) => b.text) : []),
      legacyPath: page ? page.path : null,
      images: page ? page.images : [],
    };
  });

  const videos = read('videos');
  const c = {
    site, venues, series, legacy, legacyBy, events, artists, videos,
    stories: read('stories').sort((a, b) => b.published.localeCompare(a.published)),
    listen: read('listen'),
    chorus: read('chorus'),
  };
  validate(c);
  c.index = buildIndex(c);
  return c;
}

export function validate(c) {
  const errors = [];
  const uniq = (kind, list, key = 'slug') => {
    const seen = new Set();
    for (const x of list) {
      if (!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(x[key] || '')) errors.push(`${kind}: bad slug "${x[key]}"`);
      if (seen.has(x[key])) errors.push(`${kind}: duplicate slug "${x[key]}"`);
      seen.add(x[key]);
    }
    return seen;
  };
  const artists = uniq('artists', c.artists);
  uniq('events', c.events);
  uniq('videos', c.videos);
  uniq('stories', c.stories);
  const series = uniq('series', c.series);
  const venues = uniq('venues', c.venues);
  for (const e of c.events) {
    if (Number.isNaN(Date.parse(e.start))) errors.push(`event ${e.slug}: bad date`);
    if (e.venue !== 'elsewhere' && !venues.has(e.venue)) errors.push(`event ${e.slug}: unknown venue "${e.venue}"`);
    if (e.series && !series.has(e.series)) errors.push(`event ${e.slug}: unknown series "${e.series}"`);
    for (const a of e.performers || []) if (!artists.has(a)) errors.push(`event ${e.slug}: unknown performer "${a}"`);
  }
  for (const v of c.videos) {
    if (!/^[\w-]{11}$/.test(v.youtubeId || '')) errors.push(`video ${v.slug}: bad youtubeId`);
    for (const a of v.artists || []) if (!artists.has(a)) errors.push(`video ${v.slug}: unknown artist "${a}"`);
  }
  for (const s of c.stories) for (const a of s.related?.artists || []) if (!artists.has(a)) errors.push(`story ${s.slug}: unknown artist "${a}"`);
  for (const p of c.legacy) if (!p.path.startsWith('/')) errors.push(`legacy page with bad path "${p.path}"`);
  for (const song of c.chorus?.songs || []) {
    if (!song.title || !song.artist) errors.push('chorus: song missing title/artist');
    // Lyrics are copyright: only public-domain or licensed choruses may be published.
    if (song.chorus?.length && !song.publicDomain && !song.licensed) errors.push(`chorus: "${song.title}" has lyrics but is not marked publicDomain or licensed`);
  }
  if (errors.length) throw new Error(`Content errors:\n  ${errors.slice(0, 50).join('\n  ')}`);
}

function group(list, keyFn) {
  const m = new Map();
  for (const x of list) for (const k of [].concat(keyFn(x) || [])) {
    if (!m.has(k)) m.set(k, []);
    m.get(k).push(x);
  }
  return m;
}

function buildIndex(c) {
  const by = (list) => new Map(list.map((x) => [x.slug, x]));
  const eventsByArtist = group(c.events, (e) => e.performers);
  // Who has shared a bill with whom, weighted by how often.
  const together = new Map();
  for (const e of c.events) {
    for (const a of e.performers) for (const b of e.performers) {
      if (a === b) continue;
      if (!together.has(a)) together.set(a, new Map());
      together.get(a).set(b, (together.get(a).get(b) || 0) + 1);
    }
  }
  return {
    artist: by(c.artists),
    event: by(c.events),
    video: by(c.videos),
    story: by(c.stories),
    series: by(c.series),
    venue: by(c.venues),
    eventsByArtist,
    eventsByYear: group(c.events, (e) => e.date.slice(0, 4)),
    eventsByVenue: group(c.events, (e) => e.venue),
    eventsBySeries: group(c.events, (e) => e.series),
    eventsByGenre: group(c.events, (e) => e.genres),
    artistsByGenre: group(c.artists, (a) => a.genres),
    videosByArtist: group(c.videos, (v) => v.artists),
    together,
  };
}

// Per-request helpers ("now" decides upcoming vs past).
export function queries(c, now = new Date()) {
  const ix = c.index;
  const t = now.getTime();
  // An event counts as past from midnight after it starts.
  const isPast = (e) => Date.parse(e.start) + 6 * 3600e3 < t;
  return {
    artist: (s) => ix.artist.get(s),
    event: (s) => ix.event.get(s),
    video: (s) => ix.video.get(s),
    story: (s) => ix.story.get(s),
    series: (s) => ix.series.get(s),
    venue: (s) => ix.venue.get(s),
    legacy: (p) => c.legacyBy[p],
    isPast,
    upcoming: () => c.events.filter((e) => !isPast(e)),
    past: () => c.events.filter(isPast).reverse(),
    eventsFor: (artist) => ix.eventsByArtist.get(artist) || [],
    eventsInYear: (y) => ix.eventsByYear.get(String(y)) || [],
    eventsAtVenue: (v) => ix.eventsByVenue.get(v) || [],
    eventsInSeries: (s) => ix.eventsBySeries.get(s) || [],
    eventsInGenre: (g) => ix.eventsByGenre.get(g) || [],
    artistsInGenre: (g) => ix.artistsByGenre.get(g) || [],
    videosFor: (artist) => ix.videosByArtist.get(artist) || [],
    playedWith: (artist, n = 8) => [...(ix.together.get(artist) || new Map())]
      .sort((a, b) => b[1] - a[1]).slice(0, n).map(([s, count]) => ({ artist: ix.artist.get(s), count })),
    storiesFor: ({ artist }) => c.stories.filter((s) => artist && s.related?.artists?.includes(artist)),
    years: () => [...ix.eventsByYear.keys()].sort(),
    genres: () => Object.keys(GENRE_NAMES).filter((g) => ix.eventsByGenre.has(g)),
    // Six years, six rings: nights per year, used by the archive rings.
    archiveByYear: () => [...ix.eventsByYear].sort().map(([year, list]) => ({ year, count: list.filter(isPast).length })),
    stats: () => ({
      nights: c.events.filter(isPast).length,
      artists: c.artists.filter((a) => a.appearances).length,
      venues: c.venues.length,
      since: c.events[0]?.date.slice(0, 4),
    }),
  };
}
